name: BioSimulators Dispatch

on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]

    steps:
      - name: Get tag
        id: tag
        run: echo "::set-output name=version::${GITHUB_REF#refs/tags/}"
      - name: Dispatch new release version to BioSimulators
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Continuous integration
          repo: biosimulators/Biosimulators_COBRApy
          token: ${{ secrets.BIOSIM_DISPATCH_TOKEN }}
          inputs: '{ "simulatorVersion": "${{ steps.tag.outputs.version }}", "simulatorVersionLatest": "true" }'
